/**
 * Curated pool of well-known albums whose cover art backs the logged-out
 * landing page's "wall". Entries are resolved against MusicBrainz / Cover
 * Art Archive by the same pipeline as user-requested covers, so the only
 * requirement is that artist + album search cleanly. Deliberately spans
 * eras and genres; extend freely — the wall randomises per request.
 */
export type LandingPoolEntry = { artist: string; album: string };

export const LANDING_POOL: LandingPoolEntry[] = [
  { artist: 'Pink Floyd', album: 'The Dark Side of the Moon' },
  { artist: 'Fleetwood Mac', album: 'Rumours' },
  { artist: 'The Beatles', album: 'Abbey Road' },
  { artist: 'Michael Jackson', album: 'Thriller' },
  { artist: 'Nirvana', album: 'Nevermind' },
  { artist: 'Amy Winehouse', album: 'Back to Black' },
  { artist: 'Radiohead', album: 'OK Computer' },
  { artist: 'Miles Davis', album: 'Kind of Blue' },
  { artist: 'Prince', album: 'Purple Rain' },
  { artist: 'David Bowie', album: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars' },
  { artist: 'Stevie Wonder', album: 'Songs in the Key of Life' },
  { artist: 'Marvin Gaye', album: "What's Going On" },
  { artist: 'The Clash', album: 'London Calling' },
  { artist: 'Joy Division', album: 'Unknown Pleasures' },
  { artist: 'Kendrick Lamar', album: 'To Pimp a Butterfly' },
  { artist: 'Arctic Monkeys', album: 'AM' },
  { artist: 'Tame Impala', album: 'Currents' },
  { artist: 'Adele', album: '21' },
  { artist: 'Bob Marley & The Wailers', album: 'Exodus' },
  { artist: 'Queen', album: 'A Night at the Opera' },
  { artist: 'Bruce Springsteen', album: 'Born to Run' },
  { artist: 'The Rolling Stones', album: 'Sticky Fingers' },
  { artist: 'Wu-Tang Clan', album: 'Enter the Wu-Tang (36 Chambers)' },
  { artist: 'Lauryn Hill', album: 'The Miseducation of Lauryn Hill' },
  { artist: 'Portishead', album: 'Dummy' },
  { artist: 'Massive Attack', album: 'Mezzanine' },
  { artist: 'Talking Heads', album: 'Remain in Light' },
  { artist: 'The Strokes', album: 'Is This It' },
  { artist: 'Gorillaz', album: 'Demon Days' },
  { artist: 'OutKast', album: 'Stankonia' },
  { artist: 'Daft Punk', album: 'Random Access Memories' },
  { artist: 'Billie Eilish', album: 'When We All Fall Asleep, Where Do We Go?' },
  { artist: 'Taylor Swift', album: '1989' },
  { artist: 'Dua Lipa', album: 'Future Nostalgia' },
  { artist: 'The Beach Boys', album: 'Pet Sounds' },
  { artist: 'Led Zeppelin', album: 'Led Zeppelin IV' },
  { artist: 'The Beatles', album: "Sgt. Pepper's Lonely Hearts Club Band" },
  { artist: 'The Beatles', album: 'Revolver' },
  { artist: 'Pink Floyd', album: 'Wish You Were Here' },
  { artist: 'Pink Floyd', album: 'The Wall' },
  { artist: 'Led Zeppelin', album: 'Houses of the Holy' },
  { artist: 'The Rolling Stones', album: 'Exile on Main St.' },
  { artist: 'The Rolling Stones', album: 'Let It Bleed' },
  { artist: 'The Who', album: "Who's Next" },
  { artist: 'The Doors', album: 'The Doors' },
  { artist: 'The Jimi Hendrix Experience', album: 'Are You Experienced' },
  { artist: 'Eagles', album: 'Hotel California' },
  { artist: 'Dire Straits', album: 'Brothers in Arms' },
  { artist: 'Bruce Springsteen', album: 'Born in the U.S.A.' },
  { artist: 'Elton John', album: 'Goodbye Yellow Brick Road' },
  { artist: 'Billy Joel', album: 'The Stranger' },
  { artist: 'Paul Simon', album: 'Graceland' },
  { artist: 'Simon & Garfunkel', album: 'Bridge over Troubled Water' },
  { artist: 'Carole King', album: 'Tapestry' },
  { artist: 'Joni Mitchell', album: 'Blue' },
  { artist: 'Neil Young', album: 'Harvest' },
  { artist: 'Bob Dylan', album: 'Highway 61 Revisited' },
  { artist: 'Bob Dylan', album: 'Blood on the Tracks' },
  { artist: 'The Velvet Underground', album: 'The Velvet Underground & Nico' },
  { artist: 'Queen', album: 'News of the World' },
  { artist: 'AC/DC', album: 'Back in Black' },
  { artist: "Guns N' Roses", album: 'Appetite for Destruction' },
  { artist: 'Metallica', album: 'Master of Puppets' },
  { artist: 'Black Sabbath', album: 'Paranoid' },
  { artist: 'Michael Jackson', album: 'Bad' },
  { artist: 'Prince', album: "Sign o' the Times" },
  { artist: 'Madonna', album: 'Like a Prayer' },
  { artist: 'Depeche Mode', album: 'Violator' },
  { artist: 'The Cure', album: 'Disintegration' },
  { artist: 'New Order', album: 'Power, Corruption & Lies' },
  { artist: 'Kate Bush', album: 'Hounds of Love' },
  { artist: 'Tears for Fears', album: 'Songs from the Big Chair' },
  { artist: 'U2', album: 'The Joshua Tree' },
  { artist: 'R.E.M.', album: 'Automatic for the People' },
  { artist: 'Peter Gabriel', album: 'So' },
  { artist: 'Whitney Houston', album: 'Whitney Houston' },
  { artist: 'Pearl Jam', album: 'Ten' },
  { artist: 'Soundgarden', album: 'Superunknown' },
  { artist: 'The Smashing Pumpkins', album: 'Mellon Collie and the Infinite Sadness' },
  { artist: 'Oasis', album: "(What's the Story) Morning Glory?" },
  { artist: 'Blur', album: 'Parklife' },
  { artist: 'Radiohead', album: 'Kid A' },
  { artist: 'Weezer', album: 'Weezer' },
  { artist: 'Red Hot Chili Peppers', album: 'Blood Sugar Sex Magik' },
  { artist: 'Alanis Morissette', album: 'Jagged Little Pill' },
  { artist: 'Beck', album: 'Odelay' },
  { artist: 'Björk', album: 'Debut' },
  { artist: 'Jeff Buckley', album: 'Grace' },
  { artist: 'Nine Inch Nails', album: 'The Downward Spiral' },
  { artist: 'The White Stripes', album: 'Elephant' },
  { artist: 'The Killers', album: 'Hot Fuss' },
  { artist: 'Green Day', album: 'Dookie' },
  { artist: 'Linkin Park', album: 'Hybrid Theory' },
  { artist: 'Coldplay', album: 'A Rush of Blood to the Head' },
  { artist: 'Dr. Dre', album: 'The Chronic' },
  { artist: 'Nas', album: 'Illmatic' },
  { artist: 'The Notorious B.I.G.', album: 'Ready to Die' },
  { artist: '2Pac', album: 'All Eyez on Me' },
  { artist: 'A Tribe Called Quest', album: 'The Low End Theory' },
  { artist: 'Public Enemy', album: 'It Takes a Nation of Millions to Hold Us Back' },
  { artist: 'Beastie Boys', album: "Paul's Boutique" },
  { artist: 'Jay-Z', album: 'The Blueprint' },
  { artist: 'Kanye West', album: 'My Beautiful Dark Twisted Fantasy' },
  { artist: 'Kendrick Lamar', album: 'good kid, m.A.A.d city' },
  { artist: 'Madvillain', album: 'Madvillainy' },
  { artist: "D'Angelo", album: 'Voodoo' },
  { artist: 'Erykah Badu', album: 'Baduizm' },
  { artist: 'Fugees', album: 'The Score' },
  { artist: 'Eminem', album: 'The Marshall Mathers LP' },
  { artist: 'Stevie Wonder', album: 'Innervisions' },
  { artist: 'Aretha Franklin', album: 'I Never Loved a Man the Way I Love You' },
  { artist: 'Otis Redding', album: 'Otis Blue' },
  { artist: 'Curtis Mayfield', album: 'Superfly' },
  { artist: 'Isaac Hayes', album: 'Hot Buttered Soul' },
  { artist: 'Sly & The Family Stone', album: "There's a Riot Goin' On" },
  { artist: 'John Coltrane', album: 'A Love Supreme' },
  { artist: 'The Dave Brubeck Quartet', album: 'Time Out' },
  { artist: 'Herbie Hancock', album: 'Head Hunters' },
  { artist: 'Sade', album: 'Diamond Life' },
  { artist: 'Norah Jones', album: 'Come Away with Me' },
  { artist: 'Daft Punk', album: 'Discovery' },
  { artist: 'The Prodigy', album: 'The Fat of the Land' },
  { artist: 'The Chemical Brothers', album: 'Dig Your Own Hole' },
  { artist: 'Aphex Twin', album: 'Selected Ambient Works 85-92' },
  { artist: 'Boards of Canada', album: 'Music Has the Right to Children' },
  { artist: 'Moby', album: 'Play' },
  { artist: 'Disclosure', album: 'Settle' },
  { artist: 'The Avalanches', album: 'Since I Left You' },
  { artist: 'LCD Soundsystem', album: 'Sound of Silver' },
  { artist: 'Arcade Fire', album: 'Funeral' },
  { artist: 'Bon Iver', album: 'For Emma, Forever Ago' },
  { artist: 'Fleet Foxes', album: 'Fleet Foxes' },
  { artist: 'Vampire Weekend', album: 'Vampire Weekend' },
  { artist: 'MGMT', album: 'Oracular Spectacular' },
  { artist: 'Interpol', album: 'Turn On the Bright Lights' },
  { artist: 'Arctic Monkeys', album: "Whatever People Say I Am, That's What I Am Not" },
  { artist: 'The xx', album: 'xx' },
  { artist: 'alt-J', album: 'An Awesome Wave' },
  { artist: 'Lana Del Rey', album: 'Born to Die' },
  { artist: 'Lorde', album: 'Pure Heroine' },
  { artist: 'The Weeknd', album: 'After Hours' },
  { artist: 'Tyler, the Creator', album: 'Igor' },
  { artist: 'Mac Miller', album: 'Swimming' },
  { artist: 'SZA', album: 'Ctrl' },
  { artist: 'Beyoncé', album: 'Lemonade' },
  { artist: 'Rihanna', album: 'Anti' },
  { artist: 'Harry Styles', album: 'Fine Line' },
  { artist: 'Olivia Rodrigo', album: 'Sour' },
  { artist: 'Taylor Swift', album: 'Folklore' },
  { artist: 'Phoebe Bridgers', album: 'Punisher' },
  { artist: 'Wilco', album: 'Yankee Hotel Foxtrot' },
  { artist: 'Santana', album: 'Abraxas' },
  { artist: 'ABBA', album: 'Arrival' },
  { artist: 'Blondie', album: 'Parallel Lines' },
  { artist: 'Ramones', album: 'Ramones' },
  { artist: 'Sex Pistols', album: "Never Mind the Bollocks, Here's the Sex Pistols" },
  { artist: 'The Smiths', album: 'The Queen Is Dead' },
  { artist: 'The Stone Roses', album: 'The Stone Roses' },
];
